//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> WebPageID { get; set; }
        public string EnContent { get; set; }
        public string LangContent { get; set; }
        public Nullable<bool> IsReachText { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual WebPage WebPage { get; set; }
    }
}
