//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QIC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public WebPage()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int WebPageID { get; set; }
        public Nullable<int> PageNo { get; set; }
        public string PageName { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
    }
}
